stages:
  - sonarQube

sonar:
  image: harbor.coppel.io/library/sonar-scanner:4.6
  stage: sonarQube
  tags:
    - docker
  script:
    - >-
      VERSION=`jq -r '.version' composer.json`;
      if [[ $VERSION = 'null' ]]; then VERSION=${CPL_PROJECT_VERSION:-1.0.0}; fi
    - >-
      sonar-scanner
      -Dsonar.host.url=$CPL_SONARQUBE_DEV
      -Dsonar.projectName=$CI_PROJECT_NAME
      -Dsonar.projectKey=$CPL_GRP_CENTRO:$CI_PROJECT_NAME
      -Dsonar.projectVersion=$VERSION
      -Dsonar.sourceEncoding=UTF-8
      -Dsonar.sources=./
      -Dsonar.exclusions=**/vendor/**/*
  only:
    refs:
      - merge_requests
      - master
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /\d{1,6}_\d{6}_(?i)(\w*Desarrollo\w*)/
      - $CI_COMMIT_REF_NAME == "master"
  except:
    - branches
